// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jcltepmsndheecegygpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjbHRlcG1zbmRoZWVjZWd5Z3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTc5MzcsImV4cCI6MjA2Mjk3MzkzN30.NEs0K5nlzfT2El8_xguQFk4sg0da3YEoX3ONXyF36Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);